7za.exe a dependencies.zip %GASS_DEPENDENCIES%\boost_1_57_0 ^
%GASS_DEPENDENCIES%\OpenSceneGraph-v3.2.1 ^
%GASS_DEPENDENCIES%\tbb ^
%GASS_DEPENDENCIES%\tinyxml2 ^
%GASS_DEPENDENCIES%\GASS ^
%GASS_DEPENDENCIES%\Hydrax-v0.5.1 ^
%GASS_DEPENDENCIES%\MyGUI_3.2.0 ^
%GASS_DEPENDENCIES%\ode ^
%GASS_DEPENDENCIES%\Ogre-v1-9 ^
%GASS_DEPENDENCIES%\ois ^
%GASS_DEPENDENCIES%\OpenAL1.1 ^
%GASS_DEPENDENCIES%\PagedGeometry-1.1.1 ^
%GASS_DEPENDENCIES%\SkyX-v0.4 ^
%GASS_DEPENDENCIES%\RakNet ^
%GASS_DEPENDENCIES%\qtpropertybrowser-2.5_1 ^
%GASS_DEPENDENCIES%\PhysX-v3.2.4 ^


pause