set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

set(VCPKG_FIXUP_ELF_RPATH ON)

set(osg_OPENGL_PROFILE "GL2")

if(PORT MATCHES "physx")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()
