vcpkg_fail_port_install(ON_TARGET "UWP")

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO leadcoder/gass
    REF 26c5c68e7fcc6b9dedd9ac69905ad2fd71723456
    SHA512 a3fb3ea77490410b76aa969764c5b52fb5ff4034c9677821e987788e4226aea4c8f734bd8ed1ca9755f9729a6fb355b758df6b227e5781572cdfb5364c2dd931
    HEAD_REF vcpkg
)

if (VCPKG_LIBRARY_LINKAGE STREQUAL "static")
    set(GASS_BUILDTYPE_STATIC TRUE)
else()
    set(GASS_BUILDTYPE_STATIC FALSE)
endif()

if ("sim" IN_LIST FEATURES)
	set(GASS_BUILD_SIM TRUE)
else()
	set(GASS_BUILD_SIM FALSE)
endif()

if ("force-static" IN_LIST FEATURES)
	set(GASS_BUILDTYPE_STATIC TRUE)
	vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
endif()

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DGASS_BUILDTYPE_STATIC=${GASS_BUILDTYPE_STATIC}
        -DGASS_BUILD_SIM_SAMPLES=FALSE
		-DGASS_BUILD_CORE_SAMPLES=FALSE
		-DGASS_BUILD_SIM=${GASS_BUILD_SIM}
		-DGASS_BUILD_PLUGIN_MYGUI=FALSE  
		-DGASS_BUILD_PLUGIN_OGRE=FALSE
		-DGASS_BUILD_PLUGIN_OPENAL=FALSE
		-DGASS_BUILD_PLUGIN_RAKNET=TRUE
		-DGASS_BUILD_PLUGIN_PHYSX=TRUE
		-DGASS_BUILD_PLUGIN_ODE=TRUE
		-DGASS_BUILD_PLUGIN_OSG=TRUE
		-DGASS_BUILD_PLUGIN_OSGEARTH=TRUE
		-DGASS_BUILD_PLUGIN_OIS=TRUE
		-DGASS_INSTALL_DEP_BINARIES=FALSE
		-DGASS_INSTALL_INCLUDE_DIR:STRING=include/gass
)

vcpkg_install_cmake()

vcpkg_copy_pdbs()

vcpkg_fixup_cmake_targets(CONFIG_PATH "CMake")

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include ${CURRENT_PACKAGES_DIR}/debug/share)

set(GASS_TOOL_PATH_REL ${CURRENT_PACKAGES_DIR}/tools/gass)
set(GASS_TOOL_PATH_DBG ${CURRENT_PACKAGES_DIR}/debug/tools/gass)

file(GLOB GASS_TOOLS ${CURRENT_PACKAGES_DIR}/bin/*.exe)
if(GASS_TOOLS)
	file(COPY ${GASS_TOOLS} DESTINATION ${GASS_TOOL_PATH_REL})
	file(REMOVE_RECURSE ${GASS_TOOLS})
endif()

file(GLOB GASS_TOOLS_DBG ${CURRENT_PACKAGES_DIR}/debug/bin/*.exe)

if(GASS_TOOLS_DBG)
	file(REMOVE_RECURSE ${GASS_TOOLS_DBG})
endif()

#move plugins to tools
file(GLOB GASS_PLUGINS_DBG ${CURRENT_PACKAGES_DIR}/debug/bin/GASSPlugin*.dll)
if(GASS_PLUGINS_DBG)
	file(COPY ${GASS_PLUGINS_DBG} DESTINATION ${GASS_TOOL_PATH_DBG}/plugins)
	file(REMOVE_RECURSE ${GASS_PLUGINS_DBG})
endif()

file(GLOB GASS_PLUGINS_REL ${CURRENT_PACKAGES_DIR}/bin/GASSPlugin*.dll)
if(GASS_PLUGINS_REL)
	file(COPY ${GASS_PLUGINS_REL} DESTINATION ${GASS_TOOL_PATH_REL}/plugins)
	file(REMOVE_RECURSE ${GASS_PLUGINS_REL})
endif()

#move cmake-files to share
file(GLOB GASS_CMAKE_FILES ${CURRENT_PACKAGES_DIR}/CMake/*.cmake)
file(COPY ${GASS_CMAKE_FILES} DESTINATION ${CURRENT_PACKAGES_DIR}/share/gass/CMake)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/CMake ${CURRENT_PACKAGES_DIR}/debug/CMake)

#install copyright
file(INSTALL ${SOURCE_PATH}/LGPL DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)