set CURRENT_DEP=%COMMON_DEP_HOME%\%1

SET GASS_DEPENDENCIES=%CURRENT_DEP%
SET GASS_HOME=%CURRENT_DEP%/GASS
SET BOOST_HOME=%CURRENT_DEP%/boost-v1.54
SET OGRE_HOME=%CURRENT_DEP%/Ogre-v1-9
SET OSG_HOME=%CURRENT_DEP%/OpenSceneGraph-v3.0.1






