#pragma once 

/**
	List all supported 
*/
enum LandCoverType
{
	LAND_COVER_DEFAULT,
	LAND_COVER_WATER_C1,
	LAND_COVER_WATER_C2,
	LAND_COVER_WATER_C3,
	LAND_COVER_ROAD_C1,
	LAND_COVER_ROAD_C2,
	LAND_COVER_ROAD_C3,
	LAND_COVER_ROAD_C4,
	LAND_COVER_FOREST_C1,
	LAND_COVER_FOREST_C2,
	LAND_COVER_FOREST_C3,
	LAND_COVER_FOREST_C4,
	LAND_COVER_GRASS_C1,
	LAND_COVER_GRASS_C2,
	LAND_COVER_URBAN_C1,
	LAND_COVER_URBAN_C2,
	LAND_COVER_DESERT_C1,
	
	//user defined
	LAND_COVER_UD_1,
	LAND_COVER_UD_2,
	LAND_COVER_UD_3,
	LAND_COVER_UD_4,
	LAND_COVER_UD_5,
	LAND_COVER_UD_6,
	LAND_COVER_UD_7,
	LAND_COVER_UD_8,
	LAND_COVER_UD_9,

	//used as hint for AI
	LAND_COVER_DOOR, //door area
	LAND_COVER_JUMP, // jump area
	LAND_COVER_OBSTACLE, // obstacle area

	LAND_COVER_LAST
};



