vcpkg_fail_port_install(ON_TARGET "UWP")

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO leadcoder/gass
    REF 67adb9f79b56c24fb2c4f988b01872049488ac5d
    SHA512 9df1e26a63a607438cd00e8fe6db33b68f7cf81b9f62da40482f7550ef88f7a7ba55194e53960a565844e63ab91d75ce6ab632203932fa4422b3d11b26f184cf
    HEAD_REF devel
)

set(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
set(VCPKG_POLICY_DLLS_WITHOUT_EXPORTS enabled)

if (VCPKG_LIBRARY_LINKAGE STREQUAL "static")
    set(GASS_BUILDTYPE_STATIC TRUE)
else()
    set(GASS_BUILDTYPE_STATIC FALSE)
endif()

if(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Linux")
	set(GASS_BUILD_PLUGIN_PHYSX FALSE)
	set(GASS_BUILD_PLUGIN_OSG FALSE)
	set(GASS_BUILD_MODULE_OSGEARTH FALSE)
else()
	set(GASS_BUILD_PLUGIN_PHYSX TRUE)
	set(GASS_BUILD_PLUGIN_OSG TRUE)
	set(GASS_BUILD_MODULE_OSGEARTH TRUE)
endif()

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DGASS_BUILDTYPE_STATIC=${GASS_BUILDTYPE_STATIC}
        -DGASS_BUILD_CORE=OFF
		-DGASS_BUILD_CORE_SAMPLES=OFF
		-DGASS_BUILD_SIM=ON
		-DGASS_BUILD_SIM_SAMPLES=OFF
		-DGASS_BUILD_PLUGIN_MYGUI=FALSE  
		-DGASS_BUILD_PLUGIN_OGRE=FALSE
		-DGASS_BUILD_PLUGIN_OPENAL=ON
		-DGASS_BUILD_PLUGIN_RAKNET=ON
		-DGASS_BUILD_PLUGIN_PHYSX=${GASS_BUILD_PLUGIN_PHYSX}
		-DGASS_BUILD_PLUGIN_ODE=ON
		-DGASS_BUILD_PLUGIN_OSG=${GASS_BUILD_PLUGIN_OSG}
		-DGASS_BUILD_MODULE_OSGEARTH=${GASS_BUILD_MODULE_OSGEARTH}
		-DGASS_BUILD_PLUGIN_OIS=ON
		-DGASS_INSTALL_DEP_BINARIES=OFF
		-DGASS_INSTALL_INCLUDE_DIR:STRING=include/gasssim
)

vcpkg_install_cmake()

vcpkg_copy_pdbs()

vcpkg_fixup_cmake_targets(CONFIG_PATH "CMake")

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include ${CURRENT_PACKAGES_DIR}/debug/share)

set(GASS_TOOL_PATH_REL ${CURRENT_PACKAGES_DIR}/tools/${PORT})
set(GASS_TOOL_PATH_DBG ${CURRENT_PACKAGES_DIR}/debug/tools/${PORT})

file(GLOB GASS_TOOLS ${CURRENT_PACKAGES_DIR}/bin/*.exe)
if(GASS_TOOLS)
	file(COPY ${GASS_TOOLS} DESTINATION ${GASS_TOOL_PATH_REL})
	file(REMOVE_RECURSE ${GASS_TOOLS})
endif()

file(GLOB GASS_TOOLS_DBG ${CURRENT_PACKAGES_DIR}/debug/bin/*.exe)

if(GASS_TOOLS_DBG)
	file(REMOVE_RECURSE ${GASS_TOOLS_DBG})
endif()

#move cmake-files to share
file(GLOB GASS_CMAKE_FILES ${CURRENT_PACKAGES_DIR}/CMake/*.cmake)
file(COPY ${GASS_CMAKE_FILES} DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT}/CMake)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/CMake ${CURRENT_PACKAGES_DIR}/debug/CMake)

#install copyright
file(INSTALL ${SOURCE_PATH}/LGPL DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)

