set(SKYX_INCLUDE_DIRS ${SKYX_DIR}/include/SKYX CACHE PATH "SKYX include directory" FORCE)
set(SKYX_LIBRARY_DIRS ${SKYX_DIR}/lib)

find_library(SKYX_LIBRARY_RELEASE SkyX HINTS ${SKYX_LIBRARY_DIRS} ${SKYX_LIBRARY_DIRS}/release
        PATHS ENV LIBRARY_PATH ENV LD_LIBRARY_PATH)

find_library(SKYX_LIBRARY_DEBUG SkyX_d HINTS ${SKYX_LIBRARY_DIRS} ${SKYX_LIBRARY_DIRS}/debug
        PATHS ENV LIBRARY_PATH ENV LD_LIBRARY_PATH)
		
mark_as_advanced(SKYX_LIBRARY_RELEASE SKYX_LIBRARY_DEBUG)

set(SKYX_LIBRARIES optimized ${SKYX_LIBRARY_RELEASE}
	 debug ${SKYX_LIBRARY_DEBUG})
