if (NOT "$ENV{RAKNET_DIR}" STREQUAL "")
	set (RAKNET_DIR $ENV{RAKNET_DIR})
endif()

find_path(RAKNET_INCLUDE_DIRS RakNetVersion.h PATHS ${RAKNET_DIR}/Source)
set(RAKNET_LIBRARY_DIRS ${RAKNET_DIR}/lib)

find_library(RAKNET_LIBRARY_RELEASE RakNet HINTS ${RAKNET_LIBRARY_DIRS} ${RAKNET_LIBRARY_DIRS}/release)
find_library(RAKNET_LIBRARY_DEBUG RakNet_d HINTS ${RAKNET_LIBRARY_DIRS} ${RAKNET_LIBRARY_DIRS}/debug)
		
mark_as_advanced(RAKNET_LIBRARY_RELEASE RAKNET_LIBRARY_DEBUG)

set(RAKNET_LIBRARIES optimized ${RAKNET_LIBRARY_RELEASE}
	 debug ${RAKNET_LIBRARY_DEBUG})
