set(HYDRAX_INCLUDE_DIRS ${HYDRAX_DIR}/include CACHE PATH "Hydrax include directory" FORCE)
set(HYDRAX_LIBRARY_DIRS ${HYDRAX_DIR}/lib)

find_library(HYDRAX_LIBRARY_RELEASE Hydrax HINTS ${HYDRAX_LIBRARY_DIRS} ${HYDRAX_LIBRARY_DIRS}/release
        PATHS ENV LIBRARY_PATH ENV LD_LIBRARY_PATH)

find_library(HYDRAX_LIBRARY_DEBUG Hydrax_d HINTS ${HYDRAX_LIBRARY_DIRS} ${HYDRAX_LIBRARY_DIRS}/debug
        PATHS ENV LIBRARY_PATH ENV LD_LIBRARY_PATH)
		
mark_as_advanced(HYDRAX_LIBRARY_RELEASE HYDRAX_LIBRARY_DEBUG)

set(HYDRAX_LIBRARIES optimized ${HYDRAX_LIBRARY_RELEASE}
	 debug ${HYDRAX_LIBRARY_DEBUG})
