

if (NOT "$ENV{GASS_HOME}" STREQUAL "")
	set (GASS_DIR $ENV{GASS_HOME} CACHE PATH "GASS home")
endif()
#set(GASS_DIR $ENV{GASS_HOME} CACHE PATH "HFE GASS folder")

#folder holding pre-compiled dependencies
set(GASS_DEPENDENCIES_DIR $ENV{GASS_DEPENDENCIES} CACHE PATH "3rd-party dependency folder")

find_package(GASSCoreThirdParty)
find_package(GASSSimThirdParty)

set(GASS_SIM_INCLUDE_DIRS ${GASS_DIR}/include ${GASS_DIR}/source ${Boost_INCLUDE_DIRS}  ${TINYXML2_INCLUDE_DIRS} ${TBB_INCLUDE_DIRS} ${ANGELSCRIPT_INCLUDE_DIRS})
set(GASS_LIBRARY_DIRS ${GASS_DIR}/lib ${GASS_DIR}/lib/debug ${GASS_DIR}/lib/release)
set(GASS_BINARY_DIRS ${GASS_DIR}/bin ${GASS_DIR}/bin/debug ${GASS_DIR}/bin/release)

find_library(GASS_CORE_LIBRARY_RELEASE GASSCore HINTS ${GASS_LIBRARY_DIRS})
find_library(GASS_CORE_LIBRARY_DEBUG GASSCore_d HINTS ${GASS_LIBRARY_DIRS})

find_library(GASS_SIM_LIBRARY_RELEASE GASSSim HINTS ${GASS_LIBRARY_DIRS})
find_library(GASS_SIM_LIBRARY_DEBUG GASSSim_d HINTS ${GASS_LIBRARY_DIRS})

set(GASS_SIM_LIBRARIES optimized ${GASS_SIM_LIBRARY_RELEASE}
	 optimized ${GASS_CORE_LIBRARY_RELEASE}
	 debug ${GASS_CORE_LIBRARY_DEBUG}
	 debug ${GASS_SIM_LIBRARY_DEBUG}
	 ${Boost_LIBRARIES}
	 ${TINYXML2_LIBRARIES}
	 ${TBB_LIBRARIES})
	 
find_library(GASS_EDITOR_LIBRARY_RELEASE GASSEditorModule HINTS ${GASS_LIBRARY_DIRS} ${GASS_LIBRARY_DIRS}/release)
find_library(GASS_EDITOR_LIBRARY_DEBUG GASSEditorModule_d HINTS ${GASS_LIBRARY_DIRS} ${GASS_LIBRARY_DIRS}/debug)

set(GASS_EDITOR_LIBRARIES optimized ${GASS_EDITOR_LIBRARY_RELEASE}
						  debug ${GASS_EDITOR_LIBRARY_RELEASE})

if (WIN32)
	  find_file(GASS_CORE_BINARY_RELEASE NAMES GASSCore.dll HINTS ${GASS_BINARY_DIRS})
	  find_file(GASS_CORE_BINARY_DEBUG NAMES GASSCore_d.dll HINTS ${GASS_BINARY_DIRS})

	  find_file(GASS_SIM_BINARY_RELEASE NAMES GASSSim.dll HINTS ${GASS_BINARY_DIRS})
	  find_file(GASS_SIM_BINARY_DEBUG NAMES GASSSim_d.dll HINTS ${GASS_BINARY_DIRS})

	  find_file(GASS_EDITOR_BINARY_RELEASE NAMES GASSEditorModule.dll HINTS ${GASS_BINARY_DIRS})
	  find_file(GASS_EDITOR_BINARY_DEBUG NAMES GASSEditorModule_d.dll HINTS ${GASS_BINARY_DIRS})
	  
	   #TBB
	   find_package(TBB)
	   
	   #Set GASSSim out binaries
	   set(GASS_SIM_BINAIES_REL ${GASS_SIM_BINARY_RELEASE} 
	    ${GASS_CORE_BINARY_RELEASE}
		${TBB_BINARY_REL})
	
	   set(GASS_SIM_BINAIES_DBG ${GASS_SIM_BINARY_DEBUG} 
	    ${GASS_CORE_BINARY_DEBUG}
		${TBB_BINARY_DBG})
	
	if (";${GASSSim_FIND_COMPONENTS};" MATCHES ";OgrePlugin;")
	  #plugins
	  find_file(GASS_PLUGIN_OGRE_BINARY_RELEASE NAMES GASSPluginOgre.dll HINTS ${GASS_BINARY_DIRS})
	  find_file(GASS_PLUGIN_OGRE_BINARY_DEBUG NAMES GASSPluginOgre_d.dll HINTS ${GASS_BINARY_DIRS})
	  find_package(Ogre)
	  set(GASS_PLUGIN_OGRE_BINARIES_REL 
		${GASS_PLUGIN_OGRE_BINARY_RELEASE}
		${OGRE_BINARY_REL}
		${OGRE_Overlay_BINARY_REL}
		${OGRE_Paging_BINARY_REL}
		${OGRE_Terrain_BINARY_REL}
		${OGRE_Plugin_CgProgramManager_REL}
		${OGRE_Plugin_OctreeSceneManager_REL}
		${OGRE_Plugin_ParticleFX_REL}
		${OGRE_RenderSystem_Direct3D9_REL}
		${OGRE_RenderSystem_GL_REL}
		${OGRE_PLUGIN_DIR_REL}/cg.dll)
		
		set(GASS_PLUGIN_OGRE_BINARIES_DBG
		${GASS_PLUGIN_OGRE_BINARY_DEBUG}
		${OGRE_BINARY_DBG}
		${OGRE_Overlay_BINARY_DBG}
		${OGRE_Paging_BINARY_DBG}
		${OGRE_Terrain_BINARY_DBG}
		${OGRE_Plugin_CgProgramManager_DBG}
		${OGRE_Plugin_OctreeSceneManager_DBG}
		${OGRE_Plugin_ParticleFX_DBG}
		${OGRE_RenderSystem_Direct3D9_DBG}
		${OGRE_RenderSystem_GL_DBG}
		${OGRE_PLUGIN_DIR_DBG}/cg.dll)
		set(GASS_SIM_BINAIES_REL ${GASS_SIM_BINAIES_REL} ${GASS_PLUGIN_OGRE_BINARIES_REL})
		set(GASS_SIM_BINAIES_DBG ${GASS_SIM_BINAIES_DBG} ${GASS_PLUGIN_OGRE_BINARIES_DBG})
	 endif()  
endif()
