

if (NOT "$ENV{GASS_HOME}" STREQUAL "")
	set (GASS_DIR $ENV{GASS_HOME})
endif()
#set(GASS_DIR $ENV{GASS_HOME} CACHE PATH "HFE GASS folder")

#folder holding pre-compiled dependencies
set(GASS_DEPENDENCIES_DIR $ENV{GASS_DEPENDENCIES} CACHE PATH "3rd-party dependency folder")

find_package(GASSCoreThirdParty)
find_package(GASSSimThirdParty)

set(GASS_SIM_INCLUDE_DIRS "${GASS_DIR}/include" "${GASS_DIR}/source" ${Boost_INCLUDE_DIRS}  ${TINYXML2_INCLUDE_DIRS} ${TBB_INCLUDE_DIRS} ${ANGELSCRIPT_INCLUDE_DIRS})
set(GASS_SIM_LIBRARY_DIRS "${GASS_DIR}/lib")

find_library(GASS_CORE_LIBRARY_RELEASE GASSCore HINTS ${GASS_SIM_LIBRARY_DIRS} ${GASS_SIM_LIBRARY_DIRS}/release)
find_library(GASS_CORE_LIBRARY_DEBUG GASSCore_d HINTS ${GASS_SIM_LIBRARY_DIRS} ${GASS_SIM_LIBRARY_DIRS}/debug)

find_library(GASS_SIM_LIBRARY_RELEASE GASSSim HINTS ${GASS_SIM_LIBRARY_DIRS} ${GASS_SIM_LIBRARY_DIRS}/release)
find_library(GASS_SIM_LIBRARY_DEBUG GASSSim_d HINTS ${GASS_SIM_LIBRARY_DIRS} ${GASS_SIM_LIBRARY_DIRS}/debug)
		
set(GASS_SIM_LIBRARIES optimized ${GASS_SIM_LIBRARY_RELEASE}
	 optimized ${GASS_CORE_LIBRARY_RELEASE}
	 debug ${GASS_CORE_LIBRARY_DEBUG}
	 debug ${GASS_SIM_LIBRARY_DEBUG}
	 ${Boost_LIBRARIES}
	 ${TINYXML2_LIBRARIES}
	 ${TBB_LIBRARIES})