set(OPENAL_BIN_DIR ${GASS_DEPENDENCIES_DIR}/OpenAL1.1/bin)
set(OPENAL_INC_DIR ${GASS_DEPENDENCIES_DIR}/OpenAL1.1/include)
set(OPENAL_LIB_DIR ${GASS_DEPENDENCIES_DIR}/OpenAL1.1/lib)

set(OPENAL_LINK_LIBRARIES debug OpenAL32
			optimized OpenAL32)

set(OPENAL_BIN_FILES_DEBUG ${OPENAL_BIN_DIR}/OpenAL32.dll)
set(OPENAL_BIN_FILES_RELEASE ${OPENAL_BIN_DIR}/OpenAL32.dll)

