if (NOT "$ENV{RAKNET_HOME}" STREQUAL "")
	set (RAKNET_DIR $ENV{RAKNET_HOME})
endif()

find_path(RAKNET_INCLUDE_DIRS RakNetVersion.h PATHS ${RAKNET_DIR}/Source ${RAKNET_DIR}/include/raknet)
set(RAKNET_LIBRARY_DIRS ${RAKNET_DIR}/lib)

find_library(RAKNET_LIBRARY_RELEASE RakNet HINTS ${RAKNET_LIBRARY_DIRS} ${RAKNET_LIBRARY_DIRS}/release)
find_library(RAKNET_LIBRARY_DEBUG RakNet_d RakNet HINTS ${RAKNET_LIBRARY_DIRS} ${RAKNET_LIBRARY_DIRS}/debug)

set(RAKNET_LIBRARIES optimized ${RAKNET_LIBRARY_RELEASE}
	 debug ${RAKNET_LIBRARY_DEBUG})
