if (NOT "$ENV{HYDRAX_HOME}" STREQUAL "")
	set (HYDRAX_DIR $ENV{HYDRAX_HOME})
endif()

find_path(HYDRAX_INCLUDE_DIRS Hydrax/Hydrax.h PATHS ${HYDRAX_DIR}/include)
set(HYDRAX_LIBRARY_DIRS ${HYDRAX_DIR}/lib)

find_library(HYDRAX_LIBRARY_RELEASE Hydrax HINTS ${HYDRAX_LIBRARY_DIRS} ${HYDRAX_LIBRARY_DIRS}/release)
find_library(HYDRAX_LIBRARY_DEBUG Hydrax_d Hydrax HINTS ${HYDRAX_LIBRARY_DIRS} ${HYDRAX_LIBRARY_DIRS}/debug)

set(HYDRAX_LIBRARIES optimized ${HYDRAX_LIBRARY_RELEASE}
	 debug ${HYDRAX_LIBRARY_DEBUG})
