if (NOT "$ENV{RAKNET4_HOME}" STREQUAL "")
	set (RAKNET4_DIR $ENV{RAKNET4_HOME})
endif()

find_path(RAKNET4_INCLUDE_DIRS RakNetVersion.h PATHS ${RAKNET4_DIR}/Source ${RAKNET4_DIR}/include/raknet)
set(RAKNET4_LIBRARY_DIRS ${RAKNET4_DIR}/lib)

find_library(RAKNET4_LIBRARY_RELEASE RakNet HINTS ${RAKNET4_LIBRARY_DIRS} ${RAKNET4_LIBRARY_DIRS}/release)
find_library(RAKNET4_LIBRARY_DEBUG RAKNET4_d RakNet HINTS ${RAKNET4_LIBRARY_DIRS} ${RAKNET4_LIBRARY_DIRS}/debug)

set(RAKNET4_LIBRARIES optimized ${RAKNET4_LIBRARY_RELEASE}
	 debug ${RAKNET4_LIBRARY_DEBUG})
