# Find OIS includes and library
#
# This module defines
#  OIS_INCLUDE_DIRS
#  OIS_LIBRARIES, the libraries to link against to use OIS.
#  OIS_FOUND, If false, do not try to use OIS

if (NOT "$ENV{OIS_HOME}" STREQUAL "")
	set (OIS_DIR $ENV{OIS_HOME})
endif()

IF (OIS_DIR)
	SET(OIS_FIND_QUIETLY TRUE) # Already in cache, be silent
ELSEIF (NOT OIS_FIND_QUIETLY)
	MESSAGE(STATUS "Looking for OIS")
ENDIF ()

SET(OIS_INCLUDE_SEARCH_DIRS
	${OIS_DIR}/includes
	${OIS_DIR}/include
	${CMAKE_LIBRARY_PATH}
	/usr/include
	/usr/local/include
	/usr/include/ois
	/opt/include
	/opt/OIS/include
)

SET(OIS_LIBRARY_SEARCH_DIRS
	${OIS_DIR}/lib
	${OIS_DIR}/lib/debug
	${OIS_DIR}/lib/release
	${CMAKE_LIBRARY_PATH}
	/usr/lib
	/usr/local/lib
	/opt/lib
	/opt/CEGUI/lib
)
SET(OIS_BINARY_SEARCH_DIRS
	${OIS_DIR}/bin)

FIND_PATH(OIS_INCLUDE_DIRS OIS.h PATHS ${OIS_INCLUDE_SEARCH_DIRS} PATH_SUFFIXES "ois" "OIS")
FIND_LIBRARY(OIS_LIBRARY_REL NAMES OIS PATHS ${OIS_LIBRARY_SEARCH_DIRS})
FIND_LIBRARY(OIS_LIBRARY_DBG NAMES OIS_d OIS PATHS ${OIS_LIBRARY_SEARCH_DIRS})
if (OIS_LIBRARY_REL AND OIS_LIBRARY_DBG)
  set(OIS_LIBRARIES optimized ${OIS_LIBRARY_REL} debug ${OIS_LIBRARY_DBG})
elseif (OIS_LIBRARY_REL)
  set(OIS_LIBRARIES ${OIS_LIBRARY_REL})
elseif (OIS_LIBRARY_DBG)
  set(OIS_LIBRARIES ${OIS_LIBRARY_DBG})
endif ()  

#ADDED BY JH
if (WIN32)
	  find_file(OIS_BINARY_REL NAMES "OIS.dll" HINTS ${OIS_BINARY_SEARCH_DIRS} ${OIS_BINARY_SEARCH_DIRS}/release)
	  find_file(OIS_BINARY_DBG NAMES "OIS_d.dll" HINTS ${OIS_BINARY_SEARCH_DIRS} ${OIS_BINARY_SEARCH_DIRS}/debug)
	  MARK_AS_ADVANCED(OIS_BINARY_REL NAMES OIS_BINARY_DBG)
endif()

MARK_AS_ADVANCED(OIS_INCLUDE_DIRS OIS_LIBRARIES OIS_LIBRARY_REL OIS_LIBRARY_DBG)

IF (OIS_INCLUDE_DIRS AND OIS_LIBRARIES)
	SET(OIS_FOUND TRUE)
ENDIF ()

IF (OIS_FOUND)
	set(TARGET_NAME ois::ois)
	if(NOT TARGET ${TARGET_NAME})
		add_library(${TARGET_NAME} UNKNOWN IMPORTED)
		set_target_properties(${TARGET_NAME} PROPERTIES
				INTERFACE_INCLUDE_DIRECTORIES ${OIS_INCLUDE_DIRS}
				IMPORTED_LOCATION ${OIS_LIBRARY_REL}
				IMPORTED_LOCATION_DEBUG ${OIS_LIBRARY_DBG})
    endif()

	IF (NOT OIS_FIND_QUIETLY)
		MESSAGE(STATUS "  libraries : ${OIS_LIBRARIES}")
		MESSAGE(STATUS "  includes  : ${OIS_INCLUDE_DIRS}")
	ENDIF ()
ELSE ()
	IF (OIS_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find OIS")
	ENDIF ()
ENDIF ()
