find_package(OpenAL REQUIRED)
IF (OPENAL_FOUND)
	set(TARGET_NAME openal::openal)
	if(NOT TARGET ${TARGET_NAME})
		add_library(${TARGET_NAME} UNKNOWN IMPORTED)
		set_target_properties(${TARGET_NAME} PROPERTIES
				INTERFACE_INCLUDE_DIRECTORIES ${OPENAL_INCLUDE_DIR}
				IMPORTED_LOCATION ${OPENAL_LIBRARY}
				IMPORTED_LOCATION_DEBUG ${OPENAL_LIBRARY})
    endif()
endif()