
if (NOT "$ENV{MYGUI_HOME}" STREQUAL "")
	 set(MYGUI_DIR $ENV{MYGUI_HOME})
endif()

find_path(MYGUI_INCLUDE_DIRS mygui.h PATHS ${MYGUI_DIR}/include/MYGUI)
set(MYGUI_LIBRARY_DIRS ${MYGUI_DIR}/lib ${MYGUI_DIR}/lib/release ${MYGUI_DIR}/lib/debug)

find_library(MYGUI_ENGINE_LIBRARY_REL MyGUIEngine HINTS ${MYGUI_LIBRARY_DIRS} )
find_library(MYGUI_ENGINE_LIBRARY_DBG MyGUIEngine_d HINTS ${MYGUI_LIBRARY_DIRS} )

find_library(MYGUI_OGREPLATFORM_LIBRARY_REL MyGUI.OgrePlatform HINTS ${MYGUI_LIBRARY_DIRS} )
find_library(MYGUI_OGREPLATFORM_LIBRARY_DBG MyGUI.OgrePlatform_d HINTS ${MYGUI_LIBRARY_DIRS} )

find_library(MYGUI_OPENGLPLATFORM_LIBRARY_REL MyGUI.OpenGLPlatform HINTS ${MYGUI_LIBRARY_DIRS} )
find_library(MYGUI_OPENGLPLATFORM_LIBRARY_DBG MyGUI.OpenGLPlatform_d HINTS ${MYGUI_LIBRARY_DIRS} )

set(MYGUI_LIBRARIES optimized ${MYGUI_ENGINE_LIBRARY_REL}
	optimized ${MYGUI_OGREPLATFORM_LIBRARY_REL}
	optimized ${MYGUI_OPENGLPLATFORM_LIBRARY_REL}
	 debug ${MYGUI_ENGINE_LIBRARY_DBG}
	 debug ${MYGUI_OGREPLATFORM_LIBRARY_DBG}
	 debug ${MYGUI_OPENGLPLATFORM_LIBRARY_DBG}
)
	 
if (WIN32)
	  set(MYGUI_BINARY_DIRS ${MYGUI_DIR}/bin ${MYGUI_DIR}/bin/debug ${MYGUI_DIR}/bin/release)
	  find_file(MYGUI_BINARY_REL NAMES MyGUIEngine.dll HINTS ${MYGUI_BINARY_DIRS})
	  find_file(MYGUI_BINARY_DBG NAMES MyGUIEngine_d.dll HINTS ${MYGUI_BINARY_DIRS})
	  
	  set(MYGUI_BINARIES_REL ${MYGUI_BINARY_REL})
	  set(MYGUI_BINARIES_DBG ${MYGUI_BINARY_DBG})
endif()
