if (NOT "$ENV{TINYXML2_HOME}" STREQUAL "")
  set(TINYXML2_DIR $ENV{TINYXML2_HOME})
else()
  find_package(PkgConfig)
  if(PKGCONFIG_FOUND)
    pkg_check_modules(PK_TINYXML2 REQUIRED tinyxml2)
#    pkg_check_modules(PK_TINYXML2_DEBUG REQUIRED tinyxml2-debug)
  endif()
endif()

find_path(TINYXML2_INCLUDE_DIRS tinyxml2.h PATHS ${TINYXML2_DIR}/include ${PK_TINYXML2_INCLUDE_DIRS})

set(TINYXML2_LIBRARY_DIRS ${TINYXML2_DIR}/lib)

find_library(TINYXML2_LIBRARY tinyxml2 HINTS PATHS ${TINYXML2_LIBRARY_DIRS} ${TINYXML2_LIBRARY_DIRS}/release ${PK_TINYXML2_LIBRARY_DIRS})
find_library(TINYXML2_LIBRARY_DEBUG tinyxml2_d HINTS PATHS ${TINYXML2_LIBRARY_DIRS} ${TINYXML2_LIBRARY_DIRS}/debug ${PK_TINYXML2_DEBUG_LIBRARY_DIRS})		

set(TINYXML2_LIBRARIES optimized ${TINYXML2_LIBRARY}
	 debug ${TINYXML2_LIBRARY_DEBUG})
