if (NOT "$ENV{RAKNET_HOME}" STREQUAL "")
	set (RAKNET_DIR $ENV{RAKNET_HOME})
endif()

find_path(RAKNET_INCLUDE_DIRS RakNetVersion.h PATHS ${RAKNET_DIR}/Source ${RAKNET_DIR}/include/raknet)
set(RAKNET_LIBRARY_DIRS ${RAKNET_DIR}/lib)

find_library(RAKNET_LIBRARY_RELEASE RakNet HINTS ${RAKNET_LIBRARY_DIRS} ${RAKNET_LIBRARY_DIRS}/release)
find_library(RAKNET_LIBRARY_DEBUG RakNet_d RakNet HINTS ${RAKNET_LIBRARY_DIRS} ${RAKNET_LIBRARY_DIRS}/debug)

IF (RAKNET_INCLUDE_DIRS AND RAKNET_LIBRARY_RELEASE AND RAKNET_LIBRARY_DEBUG)
	SET(RAKNET_FOUND TRUE)
ENDIF ()

if(RAKNET_FOUND)
	set(RAKNET_LIBRARIES optimized ${RAKNET_LIBRARY_RELEASE}
		                 debug ${RAKNET_LIBRARY_DEBUG})
						 
	set(TARGET_NAME raknet::raknet)
	if(NOT TARGET ${TARGET_NAME})
	
	add_library(${TARGET_NAME} UNKNOWN IMPORTED)
	set_target_properties(${TARGET_NAME} PROPERTIES
				INTERFACE_INCLUDE_DIRECTORIES ${RAKNET_INCLUDE_DIRS}
				IMPORTED_LOCATION ${RAKNET_LIBRARY_RELEASE}
				IMPORTED_LOCATION_DEBUG ${RAKNET_LIBRARY_DEBUG})
	endif()
	if(WIN32)
		set_target_properties(${TARGET_NAME} PROPERTIES IMPORTED_LINK_INTERFACE_LIBRARIES ws2_32)
	endif()				
endif()