if (NOT "$ENV{ANGELSCRIPT_HOME}" STREQUAL "")
	set (ANGELSCRIPT_DIR $ENV{ANGELSCRIPT_HOME})
endif()
	
find_path(ANGELSCRIPT_INCLUDE_DIRS angelscript.h PATHS ${ANGELSCRIPT_DIR}/include)

set(ANGELSCRIPT_LIBRARY_DIRS ${ANGELSCRIPT_DIR}/lib)

find_library(ANGELSCRIPT_LIBRARY Angelscript HINTS ${ANGELSCRIPT_LIBRARY_DIRS} ${ANGELSCRIPT_LIBRARY_DIRS}/release)
find_library(ANGELSCRIPT_LIBRARY_DEBUG Angelscript_d HINTS ${ANGELSCRIPT_LIBRARY_DIRS} ${ANGELSCRIPT_LIBRARY_DIRS}/debug)
		
mark_as_advanced(ANGELSCRIPT_LIBRARY ANGELSCRIPT_LIBRARY_DEBUG)

set(ANGELSCRIPT_LIBRARIES optimized ${ANGELSCRIPT_LIBRARY}
	 debug ${ANGELSCRIPT_LIBRARY_DEBUG})
