
find_package(OpenAL)

if (WIN32)
	  set(OPENAL_BIN_DIR $ENV{OPENALDIR}/bin)
	  find_file(OPENAL_BINARY_REL NAMES "OpenAL32.dll" HINTS ${OPENAL_BIN_DIR} ${OPENAL_BIN_DIR}/release)
	  find_file(OPENAL_BINARY_DBG NAMES "OpenAL32.dll" HINTS ${OPENAL_BIN_DIR} ${OPENAL_BIN_DIR}/debug)
	  set(OPENAL_BIN_FILES_RELEASE ${OPENAL_BINARY_REL})
	  set(OPENAL_BIN_FILES_DEBUG ${OPENAL_BINARY_DBG})
endif()