set(GASS_DEP_BINARIES_REL
	bz2.dll
	expat.dll
	fontconfig.dll
	freetype.dll
	gdal204.dll
	geos.dll
	geos_c.dll
	libcharset.dll
	libcurl.dll
	LIBEAY32.dll
	libiconv.dll
	libpng16.dll
	libpq.dll
	libprotobuf.dll
	libxml2.dll
	lzma.dll
	ode_double.dll
	OIS.dll
	OpenAL32.dll
	openjp2.dll
	osg160-osg.dll
	osg160-osgDB.dll
	osg160-osgGA.dll
	osg160-osgManipulator.dll
	osg160-osgShadow.dll
	osg160-osgSim.dll
	osg160-osgTerrain.dll
	osg160-osgText.dll
	osg160-osgUtil.dll
	osg160-osgViewer.dll
	osgEarth.dll
	osgEarthAnnotation.dll
	osgEarthFeatures.dll
	osgEarthSymbology.dll
	osgEarthUtil.dll
	ot21-OpenThreads.dll
	PhysXCommon_64.dll
	PhysXCooking_64.dll
	PhysXFoundation_64.dll
	PhysX_64.dll
	sqlite3.dll
	SSLEAY32.dll
	webp.dll
	zlib1.dll
	proj.dll
	#osg plugins
	osgdb_3dc.dll
	osgdb_3ds.dll
	osgdb_ac.dll
	osgdb_bmp.dll
	osgdb_bsp.dll
	osgdb_bvh.dll
	osgdb_cfg.dll
	osgdb_curl.dll
	osgdb_dds.dll
	osgdb_deprecated_osg.dll
	osgdb_deprecated_osganimation.dll
	osgdb_deprecated_osgfx.dll
	osgdb_deprecated_osgparticle.dll
	osgdb_deprecated_osgshadow.dll
	osgdb_deprecated_osgsim.dll
	osgdb_deprecated_osgterrain.dll
	osgdb_deprecated_osgtext.dll
	osgdb_deprecated_osgviewer.dll
	osgdb_deprecated_osgvolume.dll
	osgdb_deprecated_osgwidget.dll
	osgdb_dot.dll
	osgdb_dxf.dll
	osgdb_freetype.dll
	osgdb_gdal.dll
	osgdb_gif.dll
	osgdb_gles.dll
	osgdb_glsl.dll
	osgdb_gz.dll
	osgdb_hdr.dll
	osgdb_ive.dll
	osgdb_jp2.dll
	osgdb_jpeg.dll
	osgdb_ktx.dll
	osgdb_logo.dll
	osgdb_lua.dll
	osgdb_lwo.dll
	osgdb_lws.dll
	osgdb_md2.dll
	osgdb_mdl.dll
	osgdb_normals.dll
	osgdb_obj.dll
	osgdb_ogr.dll
	osgdb_openflight.dll
	osgdb_osc.dll
	osgdb_osg.dll
	osgdb_osga.dll
	osgdb_osgjs.dll
	osgdb_osgshadow.dll
	osgdb_osgterrain.dll
	osgdb_osgtgz.dll
	osgdb_osgviewer.dll
	osgdb_p3d.dll
	osgdb_pic.dll
	osgdb_ply.dll
	osgdb_png.dll
	osgdb_pnm.dll
	osgdb_pov.dll
	osgdb_pvr.dll
	osgdb_revisions.dll
	osgdb_rgb.dll
	osgdb_rot.dll
	osgdb_scale.dll
	osgdb_serializers_osg.dll
	osgdb_serializers_osganimation.dll
	osgdb_serializers_osgfx.dll
	osgdb_serializers_osgga.dll
	osgdb_serializers_osgmanipulator.dll
	osgdb_serializers_osgparticle.dll
	osgdb_serializers_osgshadow.dll
	osgdb_serializers_osgsim.dll
	osgdb_serializers_osgterrain.dll
	osgdb_serializers_osgtext.dll
	osgdb_serializers_osgui.dll
	osgdb_serializers_osgutil.dll
	osgdb_serializers_osgviewer.dll
	osgdb_serializers_osgvolume.dll
	osgdb_shp.dll
	osgdb_stl.dll
	osgdb_tf.dll
	osgdb_tga.dll
	osgdb_tgz.dll
	osgdb_tiff.dll
	osgdb_trans.dll
	osgdb_trk.dll
	osgdb_txf.dll
	osgdb_txp.dll
	osgdb_vtf.dll
	osgdb_x.dll
	osgdb_zip.dll
	osgdb_earth.dll
	osgdb_fastdxt.dll
	osgdb_gltf.dll
	osgdb_kml.dll
	osgdb_osgearth_agglite.dll
	osgdb_osgearth_arcgis.dll
	osgdb_osgearth_bing.dll
	osgdb_osgearth_bumpmap.dll
	osgdb_osgearth_cache_filesystem.dll
	osgdb_osgearth_cesiumion.dll
	osgdb_osgearth_colorramp.dll
	osgdb_osgearth_debug.dll
	osgdb_osgearth_detail.dll
	osgdb_osgearth_engine_mp.dll
	osgdb_osgearth_engine_rex.dll
	osgdb_osgearth_featurefilter_intersect.dll
	osgdb_osgearth_featurefilter_join.dll
	osgdb_osgearth_feature_elevation.dll
	osgdb_osgearth_feature_mapnikvectortiles.dll
	osgdb_osgearth_feature_ogr.dll
	osgdb_osgearth_feature_tfs.dll
	osgdb_osgearth_feature_wfs.dll
	osgdb_osgearth_feature_xyz.dll
	osgdb_osgearth_gdal.dll
	osgdb_osgearth_label_annotation.dll
	osgdb_osgearth_mapinspector.dll
	osgdb_osgearth_mask_feature.dll
	osgdb_osgearth_mbtiles.dll
	osgdb_osgearth_model_feature_geom.dll
	osgdb_osgearth_model_simple.dll
	osgdb_osgearth_monitor.dll
	osgdb_osgearth_osg.dll
	osgdb_osgearth_scriptengine_javascript.dll
	osgdb_osgearth_skyview.dll
	osgdb_osgearth_sky_gl.dll
	osgdb_osgearth_sky_simple.dll
	osgdb_osgearth_terrainshader.dll
	osgdb_osgearth_tilecache.dll
	osgdb_osgearth_tileindex.dll
	osgdb_osgearth_tilepackage.dll
	osgdb_osgearth_tms.dll
	osgdb_osgearth_vdatum_egm2008.dll
	osgdb_osgearth_vdatum_egm84.dll
	osgdb_osgearth_vdatum_egm96.dll
	osgdb_osgearth_viewpoints.dll
	osgdb_osgearth_vpb.dll
	osgdb_osgearth_wcs.dll
	osgdb_osgearth_wms.dll
	osgdb_osgearth_xyz.dll
	osgdb_template.dll
	osgdb_webp.dll)

set(GASS_DEP_BINARIES_DBG
	proj_d.dll
	bz2d.dll
	expatd.dll
	fontconfig.dll
	freetyped.dll
	gdal204.dll
	geosd.dll
	geos_cd.dll
	libcharset.dll
	libcurl-d.dll
	LIBEAY32.dll
	libiconv.dll
	libpng16d.dll
	libpqd.dll
	libprotobufd.dll
	libxml2.dll
	lzmad.dll
	ode_doubled.dll
	OIS_d.dll
	OpenAL32.dll
	openjp2.dll
	osg160-osgd.dll
	osg160-osgDBd.dll
	osg160-osgGAd.dll
	osg160-osgManipulatord.dll
	osg160-osgShadowd.dll
	osg160-osgSimd.dll
	osg160-osgTerraind.dll
	osg160-osgTextd.dll
	osg160-osgUtild.dll
	osg160-osgViewerd.dll
	osgEarthAnnotationd.dll
	osgEarthd.dll
	osgEarthFeaturesd.dll
	osgEarthSymbologyd.dll
	osgEarthUtild.dll
	ot21-OpenThreadsd.dll
	PhysXCommon_64.dll
	PhysXCooking_64.dll
	PhysXFoundation_64.dll
	PhysX_64.dll
	sqlite3.dll
	SSLEAY32.dll
	webpd.dll
	zlibd1.dll
	#plugins
	osgdb_3dcd.dll
	osgdb_3dsd.dll
	osgdb_acd.dll
	osgdb_bmpd.dll
	osgdb_bspd.dll
	osgdb_bvhd.dll
	osgdb_cfgd.dll
	osgdb_curld.dll
	osgdb_ddsd.dll
	osgdb_deprecated_osganimationd.dll
	osgdb_deprecated_osgd.dll
	osgdb_deprecated_osgfxd.dll
	osgdb_deprecated_osgparticled.dll
	osgdb_deprecated_osgshadowd.dll
	osgdb_deprecated_osgsimd.dll
	osgdb_deprecated_osgterraind.dll
	osgdb_deprecated_osgtextd.dll
	osgdb_deprecated_osgviewerd.dll
	osgdb_deprecated_osgvolumed.dll
	osgdb_deprecated_osgwidgetd.dll
	osgdb_dotd.dll
	osgdb_dxfd.dll
	osgdb_freetyped.dll
	osgdb_gdald.dll
	osgdb_gifd.dll
	osgdb_glesd.dll
	osgdb_glsld.dll
	osgdb_gzd.dll
	osgdb_hdrd.dll
	osgdb_ived.dll
	osgdb_jp2d.dll
	osgdb_jpegd.dll
	osgdb_ktxd.dll
	osgdb_logod.dll
	osgdb_luad.dll
	osgdb_lwod.dll
	osgdb_lwsd.dll
	osgdb_md2d.dll
	osgdb_mdld.dll
	osgdb_normalsd.dll
	osgdb_objd.dll
	osgdb_ogrd.dll
	osgdb_openflightd.dll
	osgdb_oscd.dll
	osgdb_osgad.dll
	osgdb_osgd.dll
	osgdb_osgjsd.dll
	osgdb_osgshadowd.dll
	osgdb_osgterraind.dll
	osgdb_osgtgzd.dll
	osgdb_osgviewerd.dll
	osgdb_p3dd.dll
	osgdb_picd.dll
	osgdb_plyd.dll
	osgdb_pngd.dll
	osgdb_pnmd.dll
	osgdb_povd.dll
	osgdb_pvrd.dll
	osgdb_revisionsd.dll
	osgdb_rgbd.dll
	osgdb_rotd.dll
	osgdb_scaled.dll
	osgdb_serializers_osganimationd.dll
	osgdb_serializers_osgd.dll
	osgdb_serializers_osgfxd.dll
	osgdb_serializers_osggad.dll
	osgdb_serializers_osgmanipulatord.dll
	osgdb_serializers_osgparticled.dll
	osgdb_serializers_osgshadowd.dll
	osgdb_serializers_osgsimd.dll
	osgdb_serializers_osgterraind.dll
	osgdb_serializers_osgtextd.dll
	osgdb_serializers_osguid.dll
	osgdb_serializers_osgutild.dll
	osgdb_serializers_osgviewerd.dll
	osgdb_serializers_osgvolumed.dll
	osgdb_shpd.dll
	osgdb_stld.dll
	osgdb_tfd.dll
	osgdb_tgad.dll
	osgdb_tgzd.dll
	osgdb_tiffd.dll
	osgdb_transd.dll
	osgdb_trkd.dll
	osgdb_txfd.dll
	osgdb_txpd.dll
	osgdb_vtfd.dll
	osgdb_xd.dll
	osgdb_zipd.dll
	osgdb_earthd.dll
	osgdb_fastdxtd.dll
	osgdb_gltfd.dll
	osgdb_kmld.dll
	osgdb_osgearth_agglited.dll
	osgdb_osgearth_arcgisd.dll
	osgdb_osgearth_bingd.dll
	osgdb_osgearth_bumpmapd.dll
	osgdb_osgearth_cache_filesystemd.dll
	osgdb_osgearth_cesiumiond.dll
	osgdb_osgearth_colorrampd.dll
	osgdb_osgearth_debugd.dll
	osgdb_osgearth_detaild.dll
	osgdb_osgearth_engine_mpd.dll
	osgdb_osgearth_engine_rexd.dll
	osgdb_osgearth_featurefilter_intersectd.dll
	osgdb_osgearth_featurefilter_joind.dll
	osgdb_osgearth_feature_elevationd.dll
	osgdb_osgearth_feature_mapnikvectortilesd.dll
	osgdb_osgearth_feature_ogrd.dll
	osgdb_osgearth_feature_tfsd.dll
	osgdb_osgearth_feature_wfsd.dll
	osgdb_osgearth_feature_xyzd.dll
	osgdb_osgearth_gdald.dll
	osgdb_osgearth_label_annotationd.dll
	osgdb_osgearth_mapinspectord.dll
	osgdb_osgearth_mask_featured.dll
	osgdb_osgearth_mbtilesd.dll
	osgdb_osgearth_model_feature_geomd.dll
	osgdb_osgearth_model_simpled.dll
	osgdb_osgearth_monitord.dll
	osgdb_osgearth_osgd.dll
	osgdb_osgearth_scriptengine_javascriptd.dll
	osgdb_osgearth_skyviewd.dll
	osgdb_osgearth_sky_gld.dll
	osgdb_osgearth_sky_simpled.dll
	osgdb_osgearth_terrainshaderd.dll
	osgdb_osgearth_tilecached.dll
	osgdb_osgearth_tileindexd.dll
	osgdb_osgearth_tilepackaged.dll
	osgdb_osgearth_tmsd.dll
	osgdb_osgearth_vdatum_egm2008d.dll
	osgdb_osgearth_vdatum_egm84d.dll
	osgdb_osgearth_vdatum_egm96d.dll
	osgdb_osgearth_viewpointsd.dll
	osgdb_osgearth_vpbd.dll
	osgdb_osgearth_wcsd.dll
	osgdb_osgearth_wmsd.dll
	osgdb_osgearth_xyzd.dll
	osgdb_templated.dll
	osgdb_webpd.dll)